kernvalley/events.kernvalley.us

- css/styles/index.css
- package.json
- service-worker.js
- sw-config.js
Also updates package installation & build scripts
> Fix grid layout

- service-worker.js
- sw-config.js
Forgot to do this with last deploy, so cache means updates don't show.
> Update service worker version

- _events/2019-cork-n-fork.md
- _events/2019-rides-n-rods-toy-run.md
- _events/2019-wild-and-scenic-film-festival.md
- service-worker.js
- sw-config.js
Including:
- Wild & Scenic Film Festival
- Cork N Fork
- Rides N Rods Toy Run
> Add new events

- _config.yml
- _events/2019-cork-n-fork.md
- _events/2019-fall-festival.md
- _events/2019-horror-house-challenge.md
- _events/2019-light-up-a-life-celebration.md
- _events/2019-rides-n-rods-toy-run.md
- _events/2019-rockin-beer-and-music-festival.md
- _events/2019-wild-and-scenic-film-festival.md
- _events/coding-for-kids.md
- _events/fireworks.md
- _events/kick-off-thursday.md
- _events/kids-fishing-derby.md
- _events/whitewater-wednesday.md
- netlify.toml
- package.json
- Add event page layout with event data & article
- Update most events to have necessary data
- Events on home page can list multiple labeled prices/offers
> Update event details pages

- _config.yml
- service-worker.js
- sw-config.js
Use absolute URLs for sitemap by settings `site.url`.
Update layouts to not set service worker URL as absolute
> Bug/sitemap 

- _events/2019-wild-and-scenic-film-festival.md
- css/styles/header.css
- css/styles/index.css
- package.json
- service-worker.js
- sw-config.js
- Add home button to header
- Widen event page content on mobile
- Automatically version service worker
- Switch to running locally in development
> Enhance mobile layout and navigation

- _config.yml
- package-lock.json
- package.json
Adding "card" class to headers was causing too much padding.
> Update mobile layout on event pages

- _events/2019-59daysofcode.md
Also updates `_includes/` & `_layouts/` for better compatibility/consistency
> Add 59 Days of Code

- _config.yml
- _events/2019-wild-and-scenic-film-festival.md
Somehow, I had this as a week-long even though it's only a single day
> Fix Film Festival end date

- _config.yml
- netlify.toml
Update CSP to allow `google-analytics.com` as `script-src`.
Will need to figure out what else to allow once this runs and generates more CSP violations
> Allow GA script in CSP

- _config.yml
- _events/2019-light-up-a-life-celebration.md
- _events/coding-for-kids.md
- css/styles/home-layout.css
- css/styles/index.css
- css/styles/vars.css
- js/index.js
- netlify.toml
- sw-config.js
- Update grid layout
- Update submodules
- Add `<open-street-map>` to event pages
- Move event page date & location to sidebar
> Update design/layout & add event map (optional)

- _config.yml
- _events/2019-59daysofcode.md
- _events/2019-christmas-candlelight-stroll.md
- _events/2019-light-up-a-life-celebration.md
- _events/2019-wreaths-across-america.md
- contact.html
- index.html
- netlify.toml
- service-worker.js
- sw-config.js
- Implement `fresh` for most pages, etc.
- Add pinned pages & events to `fresh`
- Import other misc. updates
> Update service worker

- _config.yml
- _events/2019-christmas-candlelight-stroll.md
- js/index.js
- netlify.toml
- service-worker.js
- sw-config.js
Add & allow `https://unpkg.com/browse/@webcomponents/custom-elements@1.3.1/`
> Add custom elements shim

- _config.yml
- css/styles/index.css
- netlify.toml
- Allow `/collect` for GA
- Fix background size
- Hide horizontal overflow
> Fix `<body>` styles

- _events/2019-christmas-candlelight-stroll.md
- _events/2019-kernville-trail-maintenance.md
- _events/2019-light-up-a-life-celebration.md
- _events/2019-wreaths-across-america.md
Specify as maintenance
Also, update keywords for other upcoming events
> Add Kernville Nature Walk

- _config.yml
- _events/2019-christmas-in-kernville.md
- _events/2020-whiskey-flat-days.md
> Add Christmas in Kernville & Whiskey Flat Days

- _config.yml
- _events/2019-christmas-in-kernville.md
- _events/2020-whiskey-flat-days.md
- sw-config.js
Also allows caching of any `/events/*` pages
>  Update links in upcoming events

- _config.yml
- netlify.toml
> Fix bad JS preload link header

- _events/2019-kernville-trail-maintenance.md
Layouts submodule updated with support for `eventStatus`
> Update layouts & make nature walk rescheduled

- _events/2019-christmas-candlelight-stroll.md
Unfortunately, I was working with bad info and correction wasn't found until too late
> Update event date (past) and mark as rescheduled

- _config.yml
- _events/2020-whiskey-flat-days-kickoff-dinner.md
- css/styles/index.css
Also adds optional event offer URLs
> Add Whiskey Flat Days Kick Off Dinner

- _config.yml
- _events/2019-bicycling-caroling-in-kernville.md
- _events/2019-christmas-candlelight-stroll.md
- _events/2019-kernville-trail-maintenance.md
- _events/2019-light-up-a-life-celebration.md
- _events/2019-wreaths-across-america.md
> Add "Bicycle Caroling in Kernville" event

- _events/2019-bicycling-caroling-in-kernville.md
- _events/2020-whiskey-flat-days-kickoff-dinner.md
- _events/2020-whiskey-flat-days.md
- WFD & WFD Kick Off link to each other
- Update Bicycle Caroling title
- Add Parade registration link to WFD event page
> Add & update links

- _data/authors/chris-zuber.yml
- _includes/contact-form.html
- css/styles/index.css
- index.html
- js/index.js
> Add contact form

- _events/2020-whiskey-flat-days-kickoff-dinner.md
In-store purachase only for remaining tickets
> Update availability of tickets online

- _config.yml
- _events/2020-kernville-nature-walk-build.md
- package-lock.json
- package.json
Also bumps version to get update to fonts via CDN
-
> Update nature walk image & description

- _events/2020-encampment-work-party.md
Creation of event spell check and syntax check required
> Created event encampment work party

- _config.yml
- _events/2020-poker-tournament-fundraiser.md
- package-lock.json
- package.json
> Fix typo in poker tournament description

- _config.yml
- css/styles/index.css
- css/styles/vars.css
- package-lock.json
- package.json
- sw-config.js
Set custom properties & use stylesheet from CDN
> Implement custom scrollbars

- _config.yml
- _events/2019-bicycling-caroling-in-kernville.md
- _events/2019-christmas-in-kernville.md
- _events/2020-encampment-work-party.md
- _events/2020-jeanette-rogers-erickson-heart-walk.md
- _events/2020-poker-tournament-fundraiser.md
- _events/2020-whiskey-flat-days-kickoff-dinner.md
- _events/2020-whiskey-flat-days.md
- service-worker.js
Also preserve original request request for fetch events in service worker
> Add JRE Heart Walk

- _events/2020-krbc-beer-pairing-dinner.md
- _includes/share-button.html
- Add phone number
- Add paired beers
- Add intermission beer
- Fix share button text & url
> Update KRBC Beer Pairing Dinner info

- _events/2020-isabella-lake-fishing-derby.md
- icons.csv
> Add Isabella Lake Fishing Derby

- _layouts/base.html
- _layouts/business-directory.html
- _layouts/default.html
- _layouts/event-page.html
- _layouts/page.html
It's too difficult to manage modifying layouts via a submodule, so convert it to a regular directory and manage directly.
Also allows setting custom URL for maps via `page.location.url`
> Convert `_layouts/` from submodule to regular directory

- _config.yml
- _data/links.yml
- add-event.html
- css/styles/index.css
- css/styles/vars.css
- icons.csv
- js/index.js
- package-lock.json
- package.json
- Add `/add-event/` page
- Add for with all needed inputs
- Add link to submit event to footer
> Add event submission form

- _events/2020-coding-for-kids.md
- _includes/event.html
- _layouts/event-page.html
> Add Coding for Kids event

- _events/2020-03-jon-ranger-band.md
- _includes/youtube.html
- icons.csv
> Add March Jon Ranger Band @ Ewings

- _includes/icon.html
- _includes/share-button.html
- _layouts/default.html
- _layouts/event-page.html
- index.html
- Better accessibility for icons
- Escaping for text/title in share button
- Add page description as text for share-buttons
- Add description & keywords to home page
-
> Misc. Enhancements

- _events/2020-isabella-lake-fishing-derby.md
Change dates, EventStatus, and add note about postponement.
Resolves #78
> Update Fishing Derby due to postponement

- _events/2020-coding-for-kids.md
- _events/2020-go-wild-kern-canyon-2.md
- _events/2020-go-wild-kern-canyon.md
- _events/2020-isabella-lake-fishing-derby.md
- _events/essential-worker-appreciation-week.md
Also mark other events as postponed or cancelled
> Add Essential Worker Appreciation Week

- _config.yml
- _includes/share-buttons.html
- _layouts/event-page.html
- css/styles/index.css
- js/index.js
- package-lock.json
- package.json
- sw-config.js
- Import component
- Add to event page layout
- Add to service worker cache
- Version bump
> Add `<share-to-button>`s to events page

- _config.yml
- _includes/event.html
- _layouts/event-page.html
- css/styles/index.css
- css/styles/status-box.css
- package-lock.json
- package.json
Still need to indicate this visually.
> Add EventAttendanceMode

- _includes/event.html
Only if something other than scheduled
> Add event status to event preview cards

- _events/2020-outlaw-west.md
- _includes/event.html
- _includes/map.html
- _includes/share-buttons.html
- _layouts/event-page.html
> Add Outlaw West as a VirtualAttendance event

- _config.yml
- package-lock.json
- package.json
Just an update to trigger refreshing of service worker & cache.
> Version bump to 1.2.22

- _events/krv-covid-19-business-roundtable.md
- _includes/share-buttons.html
- _layouts/event-page.html
Also makes share buttons customizable.
> Add KRV Covid-19 Business Roundtable Zoom meeting as event

- _events/krv-covid-19-business-roundtable.md
Should prevent overflow issues
> Add optional breaks in long URL

- _config.yml
- package-lock.json
- package.json
Triggers update in service worker cache
> Version bump to 1.2.23

- _config.yml
- _data/app.yml
- _data/icons.csv
- _data/links.yml
- _includes/footer.html
- _includes/head.html
- _includes/header.html
- css/footer.css
- css/header.css
- index.html
- package-lock.json
- package.json
- privacy.md
- Add privacy policy Resolves #104
- Fix setting referrer Resolves #105
- Add privacy policy link to footer
- Rearrange footer links
- Increase line-height for footer links & disable list style
- Fix setting sharing thumbnails
- Use `app.shortName` instead of main title on mobile
- Add iOS web app metadata
- Misc. styling updates
- Update icons
- Version bump to v1.3.1
> Add privacy policy & fix metadata

- .well-known/assetlinks.json
Add `sha256_cert_fingerprints` from Google Play signature
> Update app signature fingerprints

- .well-known/assetlinks.json
Reverts kernvalley/events.kernvalley.us#107
> Revert "Update app signature fingerprints"

- .well-known/assetlinks.json
Add all variety of signature hashes available
> Re-update cert signatures

- _data/app.yml
- manifest.json
- privacy.md
Adds Play Store data to manifest & updates privacy policy
> Add Google Play as platform in webapp manifest

- _data/app.yml
- manifest.json
- package-lock.json
- package.json
- Fix theme color. Resolves #111
- Fix setting version
- Fix setting short_name
- Make categories also set by data file
- Remove obsolete/invalid developer section
- Version bump
> Update manifest data

- .dependabot/config.yml
- .travis.yml
- CHANGELOG.md
- README.md
Automate creating pull requests with weekly checks
> Add Dependabot config & changelog

- .gitmodules
- CHANGELOG.md
It has been stored in this repo for a while now. Somehow remained in `.gitmodules` though.
> Remove `_layouts/` as submodule

- _config.yml
Use correct property names.
This fixes invalid repo URLs
> Fix repo config

- .github/dependabot.yml
- CHANGELOG.md
Add submodule config to Dependabot. Also changes GitHub Actions to weekly.
> Add submodules to dependabot

- CHANGELOG.md
- _config.yml
- _data/app.yml
- package-lock.json
- package.json
- sw-config.js
CDN update moves component styles to external stylesheets.
> Update to load stylesheets externally in components

- .github/workflows/nodejs.yml
- _includes/share-button.html
- package-lock.json
- package.json
- Add missing `.btn .btn-primary` to share button
- Misc workdflow & package updates
> Update for changes to <button> CSS

- _includes/footer.html
- _includes/keep-kern-clean.html
> Add #KeepKernClean badge

- .github/workflows/super-linter.yml
- _config.yml
- _data/preconnect.yml
- _data/preload.yml
- _events/2020-great-kern-river-cleanup.md
- _includes/event.html
- css/index.css
Also updates [Great Kern River Cleanup](https://events.kernvalley.us/events/2020-great-kern-river-cleanup/) with registration link.
> Improve preloading of assets

- CHANGELOG.md
- _config.yml
- _data/app.yml
- _data/preconnect.yml
- _data/preload.yml
- _data/scripts/development.yml
- _data/scripts/production.yml
- _data/stylesheets/development.yml
- _data/stylesheets/production.yml
- _includes/faq.html
- _includes/gravatar.html
- _includes/head.html
- _includes/imgur.html
- _includes/license.html
- _includes/preload.html
- _includes/script.html
- _includes/stylesheet.html
- contact.html
- js/index.js
- package-lock.json
- package.json
- Track external link clicks with GA
- Make properties for preloading, etc. consistent
- Update components/`_includes/`
- Use `"no-referrer"` as default referrer policy
- Disable bash script linting for issue with `.rvmrc`
> Various updates

- CHANGELOG.md
- _config.yml
- _data/app.yml
- netlify.toml
- sw-config.js
Already handled on CDN. Just needed to update stylesheet in cache & CSP
> Update to Leaflet 1.7.1

- CHANGELOG.md
- _config.yml
- _data/ads.yml
- _data/apikeys.yml
- _data/app.yml
- _data/weather.yml
- _events/2020-great-kern-river-cleanup-2.md
- _headers
- _includes/footer.html
- _includes/nav.html
- _includes/share-button.html
- _includes/share-buttons.html
- _includes/sidebar.html
- _includes/weather.html
- _layouts/base.html
- _layouts/default.html
- _layouts/event-page.html
- _layouts/page.html
- css/home-layout.css
- css/index.css
- css/nav.css
- css/sidebar.css
- index.html
- js/reset.js
- package-lock.json
- package.json
- reset.html
Import numerous updates to components, etc. and revert to using default layout instead of custom one.
> Update to use traditional site layout and style

- _data/ads.yml
- _data/app.yml
- _data/weather.yml
- _events/2020-trunk-or-treat.md
- _includes/weather.html
- _layouts/event-page.html
- css/vars.css
- index.html
- Add tmp event info for Trunk or Treat
- Implement Halloween colors
- Force dark mode on pages, ads, and weather
> Add Trick or Trunk event & implement Halloween theme

- _events/2020-halloween-drive-thru.md
- _events/2020-trunk-or-treat.md
With temp image and content.
Also adds emoji to Halloween event titles
Pushing to production since there's no reply.... What I have will just have to do for now.
> Add WIP Grocery Outlet Halloween Event

- _data/app.yml
- _layouts/event-page.html
- js/index.js
Use to determine which events have reminders scheduled
> Store scheduled notification info vioa cookies

- index.html
- js/index.js
Since Nextcloud server is no longer available, use Google Forms.
> Update URL for event submission form

- _data/ads.yml
- _data/app.yml
- _headers
- js/index.js
- Use notification permission request function
- Set time notification is scheduled for in cookie
- Update ad images to load from CDN
- Fix clearing data via `Clear-Site-Data` header
- Set headers for event pages (was set for `/posts/`)
> Various fixes and enhancements

- _data/ads.yml
- _events/2021/2021-whiskey-flat-days.md
- _headers
Unfortunately this is a cancelled event. Includes links to virtual fundraising event though.
Also fixes ad IDs and preloads main assets
> Add 2021 WFD

- _config.yml
- events.json.config
Adds `"offers"` and `"eventAttendanceMode"`. Also default value for `event.offers`.
> Update JSON encoding of events

- _layouts/event-page.html
- css/event-info.css
- css/layout.css
- sw-config.js
Move time, place, & organizer info from sidebar.
> Update event page layout

- _headers
- css/embed.css
- embed.html
- js/embed.js
Using `<krv-events>` component.
> Add events embeddable in an `<iframe>`

- js/embed.js
Use `get()` instead of `set()` for `URLSearchParams`.
> Fix setting `<krv-events source>`

- _headers
- _layouts/event-page.html
- js/index.js
- sw-config.js
> Add Disqus comments to event pages

- _events/2021/2021-keyesville-classic.md
- _events/2021/2021-rock-n-blues-fest.md
- _events/2021/2021-rockin-river-beer-and-music.md
- _includes/event.html
- css/index.css
- Update event calendar grid layout (use `masonry` if supported)
- Update offers for upcoming events with `@type`
- Improve handling of event locations on event calendar grid
- Re-add icon for event locations
> Misc. fixes & enhancements

- _config.yml
- index.html
> Update app thumbnail

- _events/2021/2021-river-run.md
> Cancel event

- _data/app.yml
- _redirects
- sw-config.js
- Add `id`
- Correctly use `webapp.webmanifest` with redirect
> Misc. PWA manifest updates

- _data/ads.yml
> Add WFD app ad

- _events/2021/paint-for-tom.md
- _events/2022/whiskey-flat-days-kickoff-dinner.md
Also add cost for Paint for Tom!
> Add WFD Kickoff Dinner for 2022

- _data/app.yml
- _events/2021/paint-for-tom.md
- js/index.js
Somehow commented out importing the module.
Also unhide share buttons when using the fallback
-  
-
> Fix share button

- _layouts/event-page.html
Support `page.location.address`
> Fix event locations

- _layouts/event-page.html
> Fix article images for events

- _data/app.yml
> Update submodule & version bump

- _events/2023/2023-02-18-wfd.md
- _headers
- css/wfd-events.css
Adds list of events to bottom of event content.
> Add `<wfd-events>` to WFD 2023 Event

- _events/2023/2023-02-18-wfd.md
- css/wfd-events.css
> Updates to `<wfd-events>`

- CHANGELOG.md
- _config.yml
- _data/app.yml
- _data/policies.yml
- _data/scripts/development.yml
- _data/scripts/production.yml
- _events/2023/2023-whiskey-flat-days-kickoff-dinner.md
- _headers
- _includes/sidebar.html
- _layouts/base.html
- _layouts/event-page.html
- js/index.js
- package-lock.json
- package.json
- sw-config.js
- Implement TrustedTypes
- Add zoom controls & fullscreen to embedded maps
- Switch from `<ad-block>` to `<krv-ad>`
- Use polyfill script from CDN instead of bundling
> Implement Trusted Types

- .github/workflows/github-release.yml
- .github/workflows/nodejs.yml
- CHANGELOG.md
- _config.yml
- _data/app.yml
- _data/importmap.yaml
- _data/scripts/development.yml
- _data/scripts/production.yml
- _headers
- package-lock.json
- package.json
> Update dependencies and config

- CHANGELOG.md
- _config.yml
- _data/app.yml
- _events/2023/2023-08-09-cowork-party.md
- _layouts/event-page.html
- css/index.css
- css/main.css
- css/vars.css
- package-lock.json
- package.json
**Added**
- Add Sierra Shared Spaces Launch / Kernville Cowork 5th Anniversary Event
**Changed**
- Move share btns to bottom of events
**Fixed**
- Fix font sizes on 4K monitors
- Fix underlined `a.btn` text
-  
-
> Add Sierra Shared Spaces / Kernville Cowork Anniversary

- CHANGELOG.md
- _config.yml
- _data/app.yml
- _events/2023/2023-08-09-cowork-party.md
- _layouts/event-page.html
- css/event-info.css
- css/index.css
- css/main.css
- package-lock.json
- package.json
Also various design updates / fixes
-  
-
> Update Cowork Party & add support for performers

- _events/2023/2023-09-01-cerf-meeting.md
> Add CERF Meeting

- _events/2023/2023-10-21-kernville-beer-and-music-festival.md
> Add 2023 Beer & Music Fest

- _events/2023/2023-11-14-krv-bridge-winter.md
> Add Get Ready for Winter in the KRV

- _data/importmap.yaml
- _data/scripts/development.yml
- _data/scripts/production.yml
- _events/2023/2023-11-29-cerf-elections.md
- _headers
- sw-config.js
> Add CERF Elections event

- CHANGELOG.md
- _config.yml
- _data/app.yml
- _data/scripts/development.yml
- _events/2023/2023-11-29-cerf-elections.md
- _headers
- embed.html
- js/embed.js
- package-lock.json
- package.json
> Fix policies and version  bump

- _events/2023/2023-11-29-cerf-elections.md
> Fix Event share image(thumbnail)

- _events/2023/2023-12-19-addiction-and-recovery.md
> Add Addiction & Recovery Pop-Up

- _events/2023/2023-12-12-geminid-meteor-shower.md
> Add Gemenid Meteor Shower Star Gazing

- _events/2023/2023-12-12-geminid-meteor-shower.md
> Update Geminids time & place

- _events/2023/2023-12-12-geminid-meteor-shower.md
> Use PNG instead of WebP event image

- CHANGELOG.md
- _data/importmap.yaml
- _data/scripts/development.yml
- _data/scripts/production.yml
- _events/2023/2023-12-19-addiction-and-recovery.md
- _events/2024/2024-01-05-wfd-kickkoff-dinner.md
- _events/2024/2024-02-16-wfd.md
- cal/krv-events.ics
- js/cal-gen.js
Also updates scripts/importmap/integrity to lastest versions.
-  
-
> Add WFD 2024 & WFD Kickoff Dinner

- _headers
> Enable CORS for iCalendar directory

- _events/2024/2024-01-24-senior-support-pop-up.md
> Add KRV Bridge Senior Support Pop-Up

- _events/2024/2024-02-11-big-game.md
> Add "The Big Game"

- _data/links.yml
- _redirects
- privacy.md
> Add privacy policy page

- events.json.config
> Fix setting event location name

- _data/importmap.json
- embed.html
> Update importmap & embed component

- CHANGELOG.md
- _config.yml
- _data/app.yml
- _data/links.yml
- _events/2024/2024-04-27-what-the-heck-is-a-community-hub.md
- _layouts/event-page.html
- css/event-info.css
- css/index.css
- css/layout.css
- css/sidebar.css
- css/vars.css
- package-lock.json
- package.json
> More design updates

- events.json.config
> Add `"keywords"` for events

- _data/importmap.json
- embed.html
- js/embed.js
> Add support for tags in emebed page

- js/create.js
> Update importing of md for events

- _events/2024/2024-05-25-memorial-day-arts-crafts-festival.md
- _includes/event.html
- create.html
- css/index.css
- js/create.js
- sw-config.js
Also updates event creation form & misc styles/templates
-  
-
> Add Day Arts & Crafts Festival

- _events/2024/2024-08-25-wilderness-survival-basic-navigation.md
> Add Wilderness Survival Course

- _events/2024/2024-05-25-wilderness-survival-basic-navigation.md
> Fix event date

- _includes/event.html
> Fix UTM params in external links

- _events/2024/2024-05-04-23rd-annual-classic-car-show.md
> Add Car Show

- _events/2024/2024-05-04-23rd-annual-classic-car-show.md
- _events/2024/2024-05-16-co-creating-our-community-hub.md
> Add Community Hub Event

- _data/importmap.json
- embed.html
> Update `@kernvalley/components` version

- _includes/event.html
- index.html
> Do not lazy load top images on home

- _events/2024/2024-05-04-building-a-fire-resilient-future.md
> Add "Building a Fire Resilient Future Award Ceremony"

- cal/krv-events.ics
> Update generated iCal

- css/event-info.css
> Update home page layout for consistency

- .gitignore
- _events/2024/2024-07-05-stars-and-stripes-independence-day-celebration.md
- _events/2024/2024-07-06-stars-and-stripes-independence-day-celebration.md
> Add 2024 Fireworks

- _events/2024/2024-07-06-independence-day-fireworks-extravaganza.md
> Rename Independence Day Fireworks Extravaganza

- cal/krv-events.ics
- js/consts.js
> Update GA code

- create.html
- Add support for specifying `@type`
- Fix bad options for organizer type
- Misc wording changes & cleanup
-  
-
> Misc updates to event creation form

- _data/app.yml
- _data/icons.yml
- _data/links.yml
- _data/tags.yml
- _events/2024/2024-06-11-lbgqt-family-and-friends-craft-night.md
- _events/2024/2024-06-15-poetry-anthology-book-reading-signing.md
- _events/2024/2024-08-09-international-co-working-day.md
- create.html
- css/index.css
- js/create.js
- js/index.js
- tags/food.html
- tags/index.html
- tags/relaxed.html
> More work on tags & N2N Events

- CHANGELOG.md
- _config.yml
- _data/app.yml
- create.html
- css/main.css
- package-lock.json
- package.json
- tags/index.html
> Update tags list/options

- _events/2024/2024-06-18-mask-making-workshop.md
- _events/2024/2024-06-21-international-yoga-day-yoga-in-the-park.md
- _events/2024/2024-07-04-4th-of-july-community-barbeque.md
- _events/2024/2024-07-21-full-moon-gathering.md
- _events/2024/2024-07-26-film-camp-premiere-community-gathering.md
- _events/2024/2024-08-02-yoga-in-the-park.md
- _events/2024/2024-08-03-community-chalk-walk-extravaganza.md
- _events/2024/2024-08-25-community-ice-cream-social.md
- _events/2024/2024-08-31-labor-day-weekend-block-parties.md
- _events/2024/2024-09-15-full-moon-gathering.md
- _events/2024/2024-09-28-good-neighbor-day-celebration.md
- _events/2024/2024-09-29-international-food-and-community-celebration.md
> Finish adding N2N events

- .github/workflows/super-linter.yml
- _events/2019/2019-12-06-christmas-candlelight-stroll.md
- _events/2020/2020-02-14-whiskey-flat-days.md
- _events/2020/2020-03-12-krbc-beer-pairing-dinner.md
- _events/2020/2020-05-16-outlaw-west.md
- _events/2021/2021-04-24-isabella-lake-fishing-derby.md
- _events/2021/2021-08-14-rubber-ducky-races.md
- _events/2022/2022-02-18-whiskey-flat-days.md
- _redirects
- sitemap.xml
> More redirect fixes

- _events/2020/2020-05-16-outlaw-west.md
- _events/2020/2020-09-12-great-kern-river-cleanup.md
- _events/2020/2020-10-31-halloween-drive-thru.md
- _events/2020/2020-10-31-trunk-or-treat.md
- _events/2020/2020-11-07-great-kern-river-cleanup-2.md
- _events/2021/2021-02-12-whiskey-flat-days.md
- _events/2021/2021-04-24-isabella-lake-fishing-derby.md
- _events/2021/2021-07-03-fireworks-extravaganza.md
- _events/2021/2021-08-14-rubber-ducky-races.md
- _events/2021/2021-09-04-art-festival.md
- _events/2021/2021-09-18-crabfest.md
- _events/2021/2021-09-18-great-kern-river-cleanup.md
- _events/2021/2021-09-23-rock-n-blues-fest.md
- _events/2021/2021-10-08-river-run.md
- _events/2021/2021-10-15-paint-4-paws.md
- _events/2021/2021-10-16-kern-river-beer-and-music.md
- _events/2021/2021-10-23-keyesville-classic.md
- _events/2021/2021-10-23-toys-for-tots-trap-shoot.md
- _events/2021/2021-12-08-paint-for-tom.md
- _events/2022/2022-02-18-whiskey-flat-days.md
- _events/2022/2022-02-26-jeanette-rogers-erickson-heart-walk.md
- _events/2023/2023-02-18-wfd.md
- _events/2023/2023-07-01-stars-and-stripes-independence-day-celebration.md
- _events/2023/2023-08-09-cowork-party.md
- _events/2024/2024-02-16-wfd.md
- _includes/event.html
- create.html
- js/create.js
Also show event link in event preview card.
And unpins all old events.
-  
-
> Add support for creating virtual events

- _events/2023/2023-08-09-cowork-party.md
- _events/2024/2024-06-02-rockslide-concert.md
- _events/2024/2024-08-02-river-rhythms.md
- _events/2024/2024-08-09-river-rhythms.md
- _events/2024/2024-08-16-river-rhythms.md
- _events/2024/2024-08-23-river-rhythms.md
- _events/2024/2024-08-30-river-rhythms.md
- _includes/event.html
- _layouts/event-page.html
- css/event-info.css
- css/nav.css
> 2024 River Rhythms event series

- _events/2024/2024-07-12-kick-and-flip.md
> Update event image

- _headers
> Fix Permissions Policy

- js/photo-booth.js
> Upload imgs before instead of after capture

- js/photo-booth.js
- photo-booth/index.html
Now uses `event.blob` on the aftercapture event to reuse captured image data.
-  
-
> Update `<photo-booth>` upload handling

- css/photo-booth.css
- js/photo-booth-dl.js
- photo-booth/download.html
Firebase rules are pretty strict on this one...
-  
-
> Add support for listing all imgs of an event

- photo-booth/download.html
- photo-booth/index.html
> Misc photo booth updates

- CHANGELOG.md
- _config.yml
- _data/app.yml
- css/photo-booth.css
- js/photo-booth-dl.js
- js/photo-booth.js
- package-lock.json
- package.json
- photo-booth/download.html
- photo-booth/index.html
Also misc fixes/updates.
-  
-
> Update photo booth download design

- _headers
> Allow Google fonts for `<photo-booth>`

- css/photo-booth.css
- js/photo-booth.js
- photo-booth/download.html
- photo-booth/index.html
> `<photo-booth>` layout/version updates

- css/photo-booth.css
- js/photo-booth.js
- photo-booth/download.html
- photo-booth/index.html
> Quick fix for photo booth orientation

- js/photo-booth.js
- photo-booth/index.html
Resolves #511
These use `Date.now().toString(36)`
-  
-
> Use `getSimpleUID` for filenames

- _events/2024/2024-08-03-back-to-school.md
- _events/2024/2024-08-09-international-co-working-day.md
Also update international coworking day
-  
-
> Add back to school event

- _events/2025/2025-01-06-community-cleanup.md
- _events/2025/2025-01-09-point-in-time.md
- _events/2025/2025-02-08-childrens-gallery-show.md
> Add some Jan 2025 events

- _events/2025/2025-01-09-point-in-time.md
> Fix PIT start time

- _events/2025/2025-03-12-geocaching-meetup.md
- _events/2025/2025-03-21-krv-cares.md
- _events/2025/2025-03-24-krv-food-drive.md
> Add N2N events for March

- _events/2025/2025-03-19-geocaching-meetup.md
> Update Geocaching Meetup

- _events/2025/2025-04-05-planting-the-seeds.md
> Add Planting the Seeds

- _events/2025/2025-07-11-kick-and-flip-360.md
- _events/2025/2025-08-08-back-to-school-movie-night.md
At least for KRV Bridge Connection. More coming soon.
-  
-
> Add other Q3 N2N events

- _events/2025/2025-10-25-kernville-fall-festival.md
> Add 2025 Kernville Fall Festival

- _events/2025/2025-09-26-krv-movie-night.md
- cal/krv-events.ics
> Fix `@type` for location

- _data/tags.yml
- _events/2025/2025-09-25-disaster-readiness-kernville.md
- _events/2025/2025-09-25-disaster-readiness-mt-mesa.md
- _events/2025/2025-09-25-kern-river-rock-n-blues-fest.md
- _events/2025/2025-09-26-krv-movie-night.md
- _events/2025/2025-10-04-disaster-readiness-lake-isabella.md
- _events/2025/2025-10-04-disaster-readiness-wofford-heights.md
- _events/2025/2025-10-07-national-night-out.md
- _events/2025/2025-10-11-magic-castle-gallery-reception.md
- _events/2025/2025-10-18-rivernook-campground-beer-and-music-festival.md
- _events/2025/2025-10-25-tricks-for-treats.md
- _events/2025/2025-12-05-internvational-volunteer-day.md
- tags/adults.html
- tags/exhibition.html
- tags/informational.html
- tags/krv-strong.html
- tags/onyx.html
- tags/seniors.html
- tags/veterans.html
- tags/youth.html
Expanded the tags list in _data/tags.yml to include 'adults', 'seniors', 'veterans', 'exhibition', 'informational', 'krv-strong', and 'onyx'. Updated multiple event files to assign these new tags where appropriate. Added new tag pages for each of the new tags to support event filtering and navigation.
-  
-
> Add new event tags and update event tag assignments

- _events/2025/2025-10-30-operation-warm-up.md
> Add Operation Warm-Up

- photo-booth/index.html
Bumped the @shgysk8zer0/components package version from 0.3.17 to 0.3.18 in the import map to use the latest release.
-  
-
> Update @shgysk8zer0/components to v0.3.18
